#!/usr/bin/env bash
# Init script to manage manage_my_process daemon

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /tmp/my_process.pid ]; then
            kill "$(cat /tmp/my_process.pid)"
            rm /tmp/my_process.pid
            echo "manage_my_process stopped"
        fi
        ;;
    restart)
        if [ -f /tmp/my_process.pid ]; then
            kill "$(cat /tmp/my_process.pid)"
            rm /tmp/my_process.pid
        fi
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
